### PR TITLE
Only use legal characters in query config name

### LINKED ISSUE #196: Strange GraphQL query
Status Code 400
```
{
  "errors": [
    {
      "message": "Syntax Error GraphQL request (1:7) Expected {, found $\n\n1: query $$_aggregated-$$_route[1]_@@default_viewer-$$_route[4]_@@default_viewer {\n         ^\n2:   viewer {\n",
      "locations": [
        {
          "line": 1,
          "column": 7
        }
      ],
      "stack": [
        "GraphQLError: Syntax Error GraphQL request (1:7) Expected {, found $",
        "",
        "1: query $$_aggregated-$$_route[1]_@@default_viewer-$$_route[4]_@@default_viewer {",
        "         ^",
        "2:   viewer {",
        "",
...
      ]
    }
  ]
}
```

GraphQL query by Relay Router:
```
"query $$_aggregated-$$_route[1]_@@default_viewer-$$_route[3]_@@default_viewer-$$_route[4]_@@default_viewer {
  viewer {
    ...F8
  }
"
```

Expected query:
```
"query ViewerQuery {
  viewer {
    ...F8
  }
}"
```

How I came across this:
There are two routes specified under Routes.js. I type in the url for Route1. Then I go to Route2, set off a Login Mutation, and I get the above error. If I stay on Route2 and refresh the page, the Login is successful. If I look at the backend, changes were made, so the mutation was successful. It is just the fetching of data that fails.

How can I go forward from here? Thanks!

### PR DESCRIPTION
**Pull request by taion**
Fixes #196

### CODE REVIEW

File: src/QueryAggregator.js [hunk 1]
```diff
@@ -109,8 +109,7 @@ export default class QueryAggregator {
       });
     });
 
-    queryConfig.name =
-      ['$$_aggregated', ...Object.keys(queryConfig.queries)].join('-');
+    queryConfig.name = 'AggregatedReactRouterQueryConfig';
```
Comment (denvned) [inline src/QueryAggregator.js]: Isn't we still need an unique query config name for a given set of queries, because `getRelayQueries` [uses](https://github.com/facebook/relay/blob/v0.9.3/src/container/getRelayQueries.js#L49) it as a part of the cache key? Otherwise Relay would probably use the set of queries belonging to the old route after changing the route to a new one (in the case the query params stay the same).

Comment (taion) [inline src/QueryAggregator.js]: Ugh yes. Hmm.

Comment (nodkz) [inline src/QueryAggregator.js]: So maybe remove `$$_` and give other prefix:
Eg.
```js
['react-router-relay', ...Object.keys(queryConfig.queries)].join('-');
```

**Comment by taion** [comment]
@denvned I'm afraid of collisions though. What do you think of https://github.com/relay-tools/react-router-relay/pull/197/commits/2cb9d20d4d6755199e2dbf5e01e75946a207d171?

**Comment by denvned** [comment]
Maybe generate route names sequentially and save them in a map where the key is `String(Object.keys(queryConfig.queries))`?

**Comment by taion** [comment]
I'm a little bit worried about non-determinism there. It means that the query names will end up being different depending on order of rendering. Wonder if this might lead to odd server/client mismatches.

**Comment by denvned** [comment]
You mean isomorphic rendering? E.g. if some app for some reason renders a query config name in a React component? Then yes, it might cause a markup mismatch.

Another alternative I can propose is just to encode the name using hex or base62.

**Comment by taion** [comment]
That's what I'm doing with `generateRQLFieldAlias`, though. Are you concerned about the Relay-internal API usage?

**Comment by denvned** [comment]
I'd prefer to avoid Relay internals, but I'm more concerned about that `generateRQLFieldAlias` encodes the hash of a name, not the name itself, and that can cause collisions, although the probability is very low.

**Comment by taion** [comment]
Okay, let's go with that: https://github.com/relay-tools/react-router-relay/pull/197/commits/2c4cbdf6873286871fa0b73c4a0cdf68a2c30e0f

@johntran Can you check if this code works?

**Comment by denvned** [comment]
I would use `__` (double `_`) to join query names to avoid some collisions, e.g. between `[foo_bar, baz]` and `[foo, bar_baz]`. Maybe I would even check that a query name doesn't contain `__` (double `_`), and doesn't start or end with `_` to completely avoid collisions. Checking that query names consist of only `/[_a-zA-Z0-9]/` could be also useful for catching user errors early.

**Comment by taion** [comment]
They do have double underscores, because I join with `_` and also start the generated query names with `_`.

I'd rather not do extra validation on user query names. I feel like it's rather unlikely to come up. I still don't have a repro for the reported issue here, even.

**Comment by johntran** [comment]
@taion The latest updates work with both default and custom network layers.

**Comment by taion** [comment]
v0.13.5
